config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :documents, except: %i[show index create] do
    member do
      patch 'autosave'
      get 'editor'
      get 'undiscard'
      get 'duplicate'
      get 'discard'
      post 'share'
    end
  end
  resources :folders do
    member do
      get 'explorer'
      get 'undiscard'
    end
    collection do
      get 'recycle_bin'
      delete 'empty_recycle_bin'
    end
  end
  resources :voices, except: :show do
    collection do
      get 'manager'
    end
    member do
      get 'undiscard'
    end
  end
  mount ActionCable.server => '/cable'
  mount DeviseMailerPreview, at: 'mail_view' if Rails.env.development?

  resources :conversations, only: [] do
    member do
      post 'new_message'
      get 'chat'
      get 'context'
      delete 'delete_message'
      get 'settings'
      patch 'update_settings'
      delete 'clear_chat'
      get 'cancel_processing'
      patch 'toggle_context'
      get 'clear_context'
    end
  end
  resources :sources, except: [:index]
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  resources :users, except: %i[new create index] do
    member do
      get 'toggle_gpt_4'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  ActiveAdmin.routes(self)

  patch '/drag/folder', to: 'drag#folder'
  patch '/drag/document', to: 'drag#document'
  get '/monitoring', to: 'monitoring#index'
  get '/wroom', to: 'wroom#app'
  get '/billing', to: 'subscriptions#subscriptions'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/redeem_referral_code', to: 'subscriptions#redeem_referral_code'
  get '/upgrade_subscription', to: 'subscriptions#upgrade_subscription'
  post '/stripe_webhook', to: 'subscriptions#stripe_webhook'
  get '/purchase_success', to: 'subscriptions#purchase_success'
  get '/dashboard', to: 'wroom#dashboard'
  get '/shared', to: 'wroom#shared'
  post '/ImportScreenplay', to: 'screenplayimporter#import_screenplay'
  get '/ImportScreenplayTest', to: 'screenplayimporter#test_form'
  root 'wroom#dashboard'
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  include Discard::Model
  belongs_to :user
  belongs_to :parent, class_name: 'Folder', optional: true
  has_many :children, class_name: 'Folder', inverse_of: :parent, foreign_key: 'parent_id', dependent: :destroy
  has_many :documents, dependent: :destroy
  # TODO: Inherit Turbo-related methods from a module
  after_discard :remove_folder_row
  after_discard :remove_from_sidebar
  # TODO: Remove reference from folders to sources from db
  after_create :add_to_sidebar
  after_save :remove_folder_row, if: :saved_change_to_parent_id?

  def parents
    return [] unless parent

    [parent] + parent.parents
  end

  def remove_from_sidebar
    broadcast_remove_to(
      user.id,
      'sidebar_explorer',
      target: "tree-folder-#{id}"
    )
  end

  def add_to_sidebar
    broadcast_append_to(
      user.id,
      'sidebar_explorer',
      partial: 'folders/tree_folder',
      locals: { folder: self },
      target: "children-of-folder-#{parent_id}"
    )
  end

  def empty?
    children.kept.empty? && documents.kept.empty?
  end

  def remove_folder_row
    broadcast_remove_to user.id, 'folders', target: "folder-row-#{id}"
  end

  def all_documents
    Document.kept.where(folder_id: all_child_folders.pluck(:id)).or(Document.kept.where(folder: self))
  end

  def all_child_folders
    Folder.kept.where(id: children.pluck(:id)).or(Folder.where(id: children.flat_map(&:all_child_folders).pluck(:id)))
  end

  def path
    build_path(self)
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at discarded_at id name parent_id type updated_at user_id]
  end

  private

  def build_path(folder)
    if folder.parent
      File.join(build_path(folder.parent), folder.name)
    else
      File.join('/', folder.name)
    end
  end
end

app/controllers/folders_controller.rb
# frozen_string_literal: true

class FoldersController < ApplicationController
  before_action :set_folder, only: %i[show edit update destroy undiscard]
  load_and_authorize_resource
  layout 'dashboard'

  def explorer
    @root_folder = current_user.root_folder
    @current_folder = params[:id].present? ? Folder.find(params[:id]) : @root_folder
  end

  def recycle_bin
    @folders = current_user.folders.discarded
    @documents = current_user.documents.discarded
    @voices = current_user.voices.discarded
  end

  def empty_recycle_bin
    @folders = current_user.folders.discarded
    @documents = current_user.documents.discarded
    @voices = current_user.voices.discarded
    @documents.destroy_all
    @folders.destroy_all
    @voices.destroy_all
    redirect_to dashboard_path
  end

  def show # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    current_user.update!(current_folder_id: @folder.id)
    # TODO: Put query logic in a service object
    @in_query = params[:query].present?
    if @in_query
      @folders = @folder.all_child_folders.where('lower(name) LIKE ?', "%#{params[:query].downcase}%")
      @documents = @folder.all_documents.where('lower(title) LIKE ?', "%#{params[:query].downcase}%")
    else
      @folders = @folder.children.kept
      @documents = @folder.documents.kept
    end
    # TODO: Move breadcrumb logic to a private method in this controller
    clear_breadcrumbs
    @folder.parents.reverse.each do |parent|
      add_breadcrumb(parent.name, folder_path(parent))
    end
    add_breadcrumb(@folder.name, folder_path(@folder))

    return unless @folder.type == 'RootFolder' && @folder.empty?

    @haiku = OpenaiService.new.haiku_about_new_venture
  end

  def new
    @folder = Folder.new
    @parent_id = current_user.current_folder_id || current_user.root_folder.id
  end

  def edit; end

  def create
    @folder = Folder.new(folder_params)
    @folder.type = 'Folder'
    if @folder.save
      current_user.update!(current_folder_id: @folder.id)
      redirect_to folder_path(@folder.parent), notice: 'Folder was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @folder.update(folder_params)
      redirect_to @folder
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @folder.discard
    @folder = @folder.parent
    head :no_content
  end

  def undiscard
    @folder.undiscard
    redirect_to @folder
  end

  private

  def set_folder
    @folder = Folder.find(params[:id])
  end

  def folder_params
    params.require(:folder).permit(:name, :user_id, :parent_id)
  end
end

app/helpers/folders_helper.rb
# frozen_string_literal: true

module FoldersHelper
end

app/views/folders/_document_row.html.erb
<% drag_actions = "dragstart->drag#drag_start dragover->drag#drag_over dragenter->drag_enter drop->drag#drop dragend->drag#drag_end" %>
<%= content_tag :tr, id: "document-row-#{document.id}", class: 'draggable', draggable: true, data: {
  controller: 'drag',
  action: drag_actions,
  resource_id: document.id,
  draggable_type: 'document',
  url: drag_document_path
} do %>
  <td onclick='document.getElementById("<%= "document-#{document.id}" %>").click();'>
    <%= link_to wroom_path(document_id: document.id), id: "document-#{document.id}", draggable: false, target: "_blank" do %>
      <% if document.source_based %>
        <i class="fa fa-book fa-fw" aria-hidden="true"></i>
      <% else %>
        <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
      <% end %>
      <%= document.title %>
    <% end %>
  </td>
  <td onclick='document.getElementById("<%= "document-#{document.id}" %>").click();'><%= document.created_at.strftime("%b %d, %Y %H:%M") %></td>
  <td onclick='document.getElementById("<%= "document-#{document.id}" %>").click();'><%= document.updated_at.strftime("%b %d, %Y %H:%M") %></td>
  <td onclick='document.getElementById("<%= "document-#{document.id}" %>").click();'>
    <%= document.source_based ? "Source" : "Document" %>
  </td>
  <td onclick='document.getElementById("<%= "document-#{document.id}" %>").click();'>
    <%= number_to_human_size(document.source.file_size) if document.source_based && document.source.present? %>
  </td>
  <% if in_query %>
    <td>
      <%= link_to folder_path(document.folder), id: "folder-#{document.folder.id}", draggable: false, data: { turbo_action: 'replace', turbo_frame: '_top' } do %>
        <i class="fa fa-arrow-right-from-bracket fa-fw" style="margin-right: 0.3rem;"></i><%= document.folder.type == 'RootFolder' ? 'My Files' : document.folder.name %>
      <% end %>
    </td>
  <% end %>
  <td>
    <%= link_to 'discard', discard_document_path(document), id: "delete-document-link-#{document.id}", style: 'display:none;'%>
    <i class="fa-solid fa-trash fa-fw delete-icon" onClick="confirmDelete('delete-document-link-<%= document.id %>', '<%= document.title.gsub(/[\"']/, '') %>')"></i>
  </td>
  <td>
    <%= link_to duplicate_document_path(document) do %>
      <i class="fa-regular fa-clone"></i>
    <% end %>
  </td>
  <td>
    <i class="fa-solid fa-grip-vertical"></i>
  </td>
<% end %>

app/views/folders/_folder_row.html.erb
<% drag_actions = "dragstart->drag#drag_start dragover->drag#drag_over dragenter->drag_enter drop->drag#drop dragend->drag#drag_end" %>
<%= content_tag :tr, id: "folder-row-#{folder.id}", class: 'draggable', draggable: true, data: {
  controller: 'drag',
  action: drag_actions,
  resource_id: folder.id,
  draggable_type: 'folder',
  url: drag_folder_path
} do %>
  <td onclick='document.getElementById("<%= "folder-#{folder.id}" %>").click();'>
    <%= link_to folder_path(folder), id: "folder-#{folder.id}", draggable: false, data: { turbo_action: 'replace', turbo_frame: '_top' } do %>
      <i class="fa fa-folder fa-fw" style="margin-right: 0.3rem;"></i><%= folder.name %>
    <% end %>
  </td>
  <td onclick='document.getElementById("<%= "folder-#{folder.id}" %>").click();'><%= folder.created_at.strftime("%b %d, %Y %H:%M") %></td>
  <td onclick='document.getElementById("<%= "folder-#{folder.id}" %>").click();'><%= folder.updated_at.strftime("%b %d, %Y %H:%M") %></td>
  <td onclick='document.getElementById("<%= "folder-#{folder.id}" %>").click();'>
    Folder
  </td>
  <td></td>
  <% if in_query %>
    <td>
      <%= link_to folder_path(folder.parent), id: "folder-#{folder.id}", draggable: false, data: { turbo_action: 'replace', turbo_frame: '_top' } do %>
        <i class="fa fa-arrow-right-from-bracket fa-fw" style="margin-right: 0.3rem;"></i><%= folder.type == 'RootFolder' ? 'My Files' : folder.name %>
      <% end %>
    </td>
  <% end %>
  <td>
    <%= button_to "❌", folder, method: :delete, id: "delete-folder-button-#{folder.id}",
    form: {
      id: 'delete-form',
      data: {
          turbo: false,
          controller: "confirmation",
          action: 'submit->confirmation#confirm',
          confirmation_message_value: "Please confirm you meant to delete #{folder.name}",
      }
    } %>
    <i class="fa-solid fa-trash fa-fw delete-icon" onClick="document.getElementById('delete-folder-button-<%= folder.id %>').click();"></i>
  </td>
  <td></td>
  <td>
    <i class="fa-solid fa-grip-vertical"></i>
  </td>
<% end %>

app/views/folders/_form.html.erb
<%= form_with(model: folder) do |form| %>
  <% if folder.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(folder.errors.count, "error") %> prohibited this folder from being saved:</h2>

      <ul>
        <% folder.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field-with-submit">
    <%= form.text_field :name, placeholder: 'Name your folder', required: true %>
    <%= form.submit 'Confirm' %>
  </div>
  <div style='display: none;'>
    <%= form.text_field :parent_id, value: parent_id, readonly: cannot?(:manage, User) %>
    <%= form.text_field :user_id, value: current_user.id, readonly: cannot?(:manage, User) %>
  </div>
<% end %>

app/views/folders/_records_table.html.erb
<%#= TODO: Find a better name for this partial and try to improve its usage %>
<%= turbo_frame_tag "records_table" do %>
  <% drag_actions = "dragstart->drag#drag_start dragover->drag#drag_over dragenter->drag_enter drop->drag#drop dragend->drag#drag_end" %>
  <% in_query = @in_query || in_query %>
  <table class="folder-contents-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Created</th>
        <th>Last accessed</th>
        <th>Type</th>
        <th>Upload size</th>
        <% if in_query %>
          <th></th>
        <% end %>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody id='draggables'>
      <% if folder && folder.type != 'RootFolder' && folder.type != 'SharedFolder' && !@in_query %>
        <%= content_tag :tr, id: "folder-row-parent",
          class: 'draggable',
          onclick: 'document.getElementById("parent_link").click();',
          data: {
          controller: 'drag',
          action: drag_actions,
          resource_id: folder.parent.id,
          draggable_type: 'folder',
          url: drag_folder_path
        } do %>
          <td>
            <%= link_to folder_path(folder.parent), id: 'parent_link', data: { turbo: "false" } do %>
            <i class="fa fa-folder fa-fw" style="margin-right: 0.3rem;"></i>..
            <% end %>
          </td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        <% end %>
      <% end %>
      <% unless folders.nil? %>
        <% folders.order(:created_at).reverse.each do |folder| %>
          <%= render 'folders/folder_row', folder: folder, in_query: in_query %>
        <% end %>
      <% end %>
      <% unless documents.nil? %>
        <% documents.order(:created_at).reverse.each do |document| %>
          <%= render 'folders/document_row', document: document, in_query: in_query %>
        <% end %>
      <% end %>
    </table>
  <% end %>

app/views/folders/_tree_document.html.erb
<%= link_to wroom_path(document_id: document.id), target: "_blank" do %>
  <div class='tree-document folder document' id="tree-document-<%= document.id %>">
    <% if document.source_based %>
      <i class="fa fa-book fa-fw" aria-hidden="true"></i>
    <% else %>
      <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
    <% end %>
    <span class='folder-name'><%= document.title %></span>
  </div>
<% end %>

app/views/folders/_tree_folder.html.erb
<%#= TODO: Find a way to decouple the usage of this partial in the sidebar from its usage in the context view %>
<%#= TODO: (app/views/conversations/context.html.erb & app/views/layouts/_sidebar.html.erb) %>
<div class='tree-folder' id="<%= "tree-folder-#{folder.id}" %>">
  <div class="folder">
    <i class="fa-solid fa-caret-down fa-sm fa-fw <%= folder.empty? ? 'invisible' : '' %>" onClick=<%= "displayChildren('tree-folder-#{folder.id}')" %>></i>
    <%= link_to folder_path(folder), data: { turbo_action: 'replace', turbo_frame: 'view_content' } do %>
      <i class="fa fa-folder fa-fw"></i><span class='folder-name'><%= folder.type == 'RootFolder' ? 'My Files' : folder.name %></span>
    <% end %>
  </div>
  <div class="children" style="display: none;" id='children-of-folder-<%= folder.id %>'>
    <% folder.children.order(:name).kept.each do |child_folder| %>
      <%= render 'folders/tree_folder', folder: child_folder %>
    <% end %>
    <% folder.documents.order(:title).kept.each do |document| %>
      <%= render 'folders/tree_document', document: document %>
    <% end %>
  </div>
</div>

app/views/folders/edit.html.erb
<div id="record-form-view">
  <div id="record-form-box">
    <div id="header">
      <h3>Rename folder</h3>
      <%= link_to "❌", explorer_folder_path(id: @folder) %>
    </div>

    <%= render "form", folder: @folder, parent_id: @folder.parent_id %>

  </div>
</div>

app/views/folders/new.html.erb
<%= turbo_frame_tag 'view_content' do %>
  <div class="header">
    <span>New folder</span>
  </div>
  <div class='new-folder'>
    <%= render "form", folder: @folder, parent_id: @parent_id %>
  </div>
<% end %>

app/views/folders/recycle_bin.html.erb
<%= turbo_frame_tag "view_content" do %>
  <%= turbo_stream_from current_user.id, "folder_documents" %>
  <div class="header">
    <span>Trash</span>
  </div>
  <% if current_user.anything_in_recycle_bin? %>
    <%= button_to "Empty the trash folder", empty_recycle_bin_folders_path, method: :delete, id: 'delete-button',
      class: 'empty-trash-button',
      form: {
        id: 'empty-trash-form',
        data: {
            turbo: false,
            controller: "confirmation",
            action: 'submit->confirmation#confirm',
            confirmation_message_value: "Please confirm you meant to permanently remove everything from trash.",
        }
      } 
    %>
  <% end %>
  <div class="recycle-bin">
    <table class="folder-contents-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created</th>
          <th>Last accessed</th>
          <th>Type</th>
          <th>Upload size</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @folders.each do |folder| %>
          <tr>
            <td>
              <i class="fa fa-folder fa-fw" style='margin-right: 0.2rem'></i><%= folder.name %>
            </td>
            <td><%= folder.created_at.strftime("%b %d, %Y %H:%M") %></td>
            <td><%= folder.updated_at.strftime("%b %d, %Y %H:%M") %></td>
            <td>
              Folder
            </td>
            <td>
            </td>
            <td>
              <%= button_to "❌", folder, method: :delete, id: "delete-folder-button-#{folder.id}",
              form: {
                id: 'delete-form',
                data: {
                    turbo: false,
                    controller: "confirmation",
                    action: 'submit->confirmation#confirm',
                    confirmation_message_value: "Please confirm you meant to IRREVOCABLY delete #{folder.name}",
                }
              } %>
              <i class="fa-solid fa-trash fa-fw delete-icon" onClick="document.getElementById('delete-folder-button-<%= folder.id %>').click();"></i>
            </td>
            <td>
              <%= link_to undiscard_folder_path(folder), data: { turbo_frame: '_top' } do %>
                <i class="fa-solid fa-trash-can-arrow-up"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% @documents.each do |document| %>
          <tr id="document-row-<%= document.id %>">
            <td>
              <% if document.source_based %>
                <i class="fa fa-book fa-fw" aria-hidden="true"></i>
              <% else %>
                <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
              <% end %>
              <%= document.title %>
            </td>
            <td><%= document.created_at.strftime("%b %d, %Y %H:%M") %></td>
            <td><%= document.updated_at.strftime("%b %d, %Y %H:%M") %></td>
            <td><%= document.updated_at.strftime("%b %d, %Y %H:%M") %></td>
            <td>
              <%= number_to_human_size(document.source.file_size) if document.source_based && document.source.present? %>
            </td>
            <td>
              <%= button_to "❌", document, method: :delete, id: "delete-document-button-#{document.id}",
              form: {
                id: 'delete-form',
                data: {
                    turbo: false,
                    controller: "confirmation",
                    action: 'submit->confirmation#confirm',
                    confirmation_message_value: "Please confirm you meant to IRREVOCABLY delete #{document.title}",
                }
              } %>
              <i class="fa-solid fa-trash fa-fw delete-icon" onClick="document.getElementById('delete-document-button-<%= document.id %>').click();"></i>
            </td>
            <td>
              <%= link_to undiscard_document_path(document), data: { turbo_frame: '_top' } do %>
                <i class="fa-solid fa-trash-can-arrow-up"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
        <% @voices.each do |voice| %>
          <tr>
            <td>
              <i class="fa-solid fa-robot" style='margin-right: 0.5rem'></i><%= voice.name %>
            </td>
            <td><%= voice.created_at.strftime("%b %d, %Y %H:%M") %></td>
            <td><%= voice.updated_at.strftime("%b %d, %Y %H:%M") %></td>
            <td>
              Voice
            </td>
            <td>
              <%= link_to undiscard_voice_path(voice), data: { turbo_frame: '_top' } do %>
                <i class="fa-solid fa-trash-can-arrow-up"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
    </table>
  </div>
<% end %>

app/views/folders/show.html.erb
<%= turbo_frame_tag 'view_content' do %>
  <%= turbo_stream_from current_user.id, 'folders' %>
  <%= turbo_stream_from current_user.id, 'folder_documents' %>
  <script>
    function confirmDelete(id, name) {
      if (confirm(`Please confirm you meant to delete ${name}`) == true) {
        document.getElementById(id).click();
      }
    }
  </script>
  <%= render partial: 'layouts/breadcrumbs' %>
  <div class="folder-content">
    <% if @folder.type == 'RootFolder' && @folder.empty? %>
      <div class="no-content">
        <h3>Welcome to WROOM</h3>
        <p>Click the "New" button to create a new folder or document.</p>
        <div class="haiku">
          <%= simple_format(@haiku) %>
        </div>
      </div>
    <% else %>
      <%= form_with(url: folder_path(@folder), method: "GET", data: {
        turbo_action: 'advance',
        turbo_frame: "records_table",
        controller: 'search'
      }, id: 'search-form' ) do |form| %>
        <i class="fa-solid fa-magnifying-glass"></i>
        <%= form.text_field :query, data: { action: 'input->search#search'} %>
        <%= form.submit 'Search', name: nil, style: 'display: none;' %>
      <% end %>
      <div class="header">
        <span><%= @folder.type == 'RootFolder' ? 'My Files' : @folder.name %></span>
        <% unless @folder.type == 'RootFolder' || @folder.type == 'SharedFolder' %>
          <div class="controls">
            <%= link_to "Rename", edit_folder_path(@folder), data: { turbo_frame: '_top' } %>
            <%= button_to "❌", @folder, method: :delete, id: 'delete-button',
              form: {
                id: 'delete-form',
                data: {
                    turbo: false,
                    controller: "confirmation",
                    action: 'submit->confirmation#confirm',
                    confirmation_message_value: "Please confirm you meant to delete #{@folder.name}"
                }
              } %>
              <i class="fa-solid fa-trash fa-fw delete-icon" onClick="document.getElementById('delete-button').click();"></i>
          </div>
        <% end %>
      </div>
      <%= render "records_table", folder: @folder, folders: @folders, documents: @documents, in_query: @in_query %>
    <% end %>
  </div>
<% end %>