config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :documents, except: %i[show index create] do
    member do
      patch 'autosave'
      get 'editor'
      get 'undiscard'
      get 'duplicate'
      get 'discard'
      post 'share'
    end
  end
  resources :folders do
    member do
      get 'explorer'
      get 'undiscard'
    end
    collection do
      get 'recycle_bin'
      delete 'empty_recycle_bin'
    end
  end
  resources :voices, except: :show do
    collection do
      get 'manager'
    end
    member do
      get 'undiscard'
    end
  end
  mount ActionCable.server => '/cable'
  mount DeviseMailerPreview, at: 'mail_view' if Rails.env.development?

  resources :conversations, only: [] do
    member do
      post 'new_message'
      get 'chat'
      get 'context'
      delete 'delete_message'
      get 'settings'
      patch 'update_settings'
      delete 'clear_chat'
      get 'cancel_processing'
      patch 'toggle_context'
      get 'clear_context'
    end
  end
  resources :sources, except: [:index]
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  resources :users, except: %i[new create index] do
    member do
      get 'toggle_gpt_4'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  ActiveAdmin.routes(self)

  patch '/drag/folder', to: 'drag#folder'
  patch '/drag/document', to: 'drag#document'
  get '/monitoring', to: 'monitoring#index'
  get '/wroom', to: 'wroom#app'
  get '/billing', to: 'subscriptions#subscriptions'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/redeem_referral_code', to: 'subscriptions#redeem_referral_code'
  get '/upgrade_subscription', to: 'subscriptions#upgrade_subscription'
  post '/stripe_webhook', to: 'subscriptions#stripe_webhook'
  get '/purchase_success', to: 'subscriptions#purchase_success'
  get '/dashboard', to: 'wroom#dashboard'
  get '/shared', to: 'wroom#shared'
  post '/ImportScreenplay', to: 'screenplayimporter#import_screenplay'
  get '/ImportScreenplayTest', to: 'screenplayimporter#test_form'
  root 'wroom#dashboard'
end

app/models/conversation.rb
# frozen_string_literal: true

class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :context_references, dependent: :destroy
  has_many :documents, through: :context_references
  has_many :usage_records, dependent: :nullify

  belongs_to :document
  has_one :user, through: :document
  has_one :conversation_voice, dependent: :destroy
  has_one :voice, through: :conversation_voice
  validates :title, presence: true
  # TODO: Inherit Turbo-related methods from a module
  after_update :broadcast_status_message

  enum role: { 'ready': 0, 'working': 1, 'idle': 2, 'error': 3, 'cancelled': 4 }

  def sources
    documents.map(&:source).compact
  end

  def clear_status_message
    update!(status_message: nil)
  end

  def cancel_processing
    return if sidekiq_job_id.blank?

    Sidekiq::Status.delete(sidekiq_job_id)
    update!(sidekiq_job_id: nil, status: 4, status_message: "Processing cancelled at #{Time.zone.now}")
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at document_id id last_query_requests sidekiq_job_id status status_message title
       total_requests updated_at]
  end

  private

  def broadcast_status_message
    return unless status_message.present? || saved_change_to_status?

    broadcast_replace_to(
      id,
      'conversation_status',
      partial: 'conversations/conversation_status',
      locals: {
        conversation: self
      },
      target: 'conversation_status'
    )
  end
end

app/controllers/conversations_controller.rb
# frozen_string_literal: true

class ConversationsController < ApplicationController
  before_action :set_conversation,
                only: %i[settings update_settings chat context toggle_context
                         new_message clear_chat cancel_processing clear_context]

  def chat
    # TODO: This cancels the processing of a user's conversations, except the current one
    # See if this hack is still necessary
    # If it is, move it to a service object or otherwise find a better way to handle it
    @conversation.user.conversations.where.not(id: @conversation.id).map(&:cancel_processing)
  end

  def context; end

  # TODO: Move this logic into the Conversation model
  def toggle_context # rubocop:disable Metrics/MethodLength
    @document = Document.find(params[:document_id])
    if @conversation.documents.include?(@document)
      ContextReference.where(
        conversation: @conversation,
        document: @document
      ).destroy_all
    else
      ContextReference.create!(
        conversation: @conversation,
        document: @document
      )
    end
    head :no_content
  end

  def clear_context
    @conversation.context_references.destroy_all # TODO: Make this a method on the Conversation model
    head :no_content
  end

  def new_message
    @conversation.update!(status: 1)
    @conversation.messages.create!(content: params[:content], role: 'user')
    sidekiq_job_id = AnswerFetchingWorker.perform_async(@conversation.id)
    @conversation.update!(sidekiq_job_id:)
    head :no_content
  end

  def delete_message
    message = Message.find(params[:message_id])
    conversation = message.conversation

    authorize! :edit, conversation
    message.discard
    head :no_content
  end

  def cancel_processing
    @conversation.messages.last.discard if @conversation.messages.any? && @conversation.messages.last.role == 'user'
    @conversation.cancel_processing
    head :no_content
  end

  def clear_chat
    authorize! :edit, @conversation
    @conversation.messages.each(&:discard)
    head :no_content
  end

  def settings; end

  def update_settings
    @conversation.update(conversation_params)
    if params[:conversation][:voice_id].present?
      ConversationVoice.find_or_create_by!(conversation: @conversation, voice_id: params[:conversation][:voice_id])
    else
      @conversation.conversation_voice&.destroy
    end
    head :no_content
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

  def conversation_params
    params.require(:conversation).permit(:title, document_ids: [])
  end
end

app/views/conversations/_conversation.html.erb
<script>
  function handleEnter(e) {
    const newMessageForm = document.getElementById('new-message-form')
    const submitButton = document.getElementById('new-message-submit')
    const newMessageTextArea = document.getElementById('new-message-text-area')
    if (e.which === 13 && !e.shiftKey) {
      e.preventDefault();
      submitButton.click();
      newMessageTextArea.value = '';
      newMessageTextArea.style.height = '1rem';
    }
  };
  document.getElementById('new-message-text-area').addEventListener('keypress', handleEnter);
</script>
<%= turbo_stream_from @conversation.id, 'chat_messages'%>
<div id='conversation'>
  <script>
    function copyContent(id) {
      const text = document.getElementById(id).innerHTML.replace(/<br>/g, "\n").replace("<p>", "").replace("</p>", "")
      navigator.clipboard.writeText(text);
    }
  </script>
  <div id='messages'>
    <% if conversation.messages.count == 0 %>
      <div id='initial-message'>
        Hello, may I be of any help?
      </div>
    <% end %>
    <% conversation.messages.kept.order(:created_at).reverse.each do |message| %>
      <% if message.role == 'error' && message.content.include?("maximum context length") %>
        <div class='message error'>
          <div class='content'>
            <div class='main-message'>
              <%= button_to('❌', delete_message_conversation_path(message.conversation, message_id: message.id), method: :delete) %>
              <div class='main-message-content'>
                You have exceeded the token limit in this conversation. If you would like to chat further,
                you can remove some messages to make space. If you would like to keep some of the content,
                copy it to your document.
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= render 'message', message: message %>
      <% end %>
    <% end %>
  </div>
  <%= render 'conversation_status', conversation: conversation %>
  <script>
  if (document.getElementById('new-message-text-area')) {
    const textarea = document.getElementById('new-message-text-area');

    textarea.addEventListener('input', () => {
        textarea.style.height = '1rem';
        textarea.style.height = `${textarea.scrollHeight}px`;
    });
  }
    function submitMessage() {
      document.getElementById('new-message-form').submit();
      document.getElementById('new-message-text-area').value = '';
    }
  </script>
  <%= form_with url: new_message_conversation_path(id: conversation.id), id: 'new-message-form' do |f| %>
    <%= f.text_area :content, required: 'required', id: 'new-message-text-area' %>
    <i class="fa-solid fa-paper-plane" onclick="submitMessage();"></i>
    <%= f.submit '➳', style: 'display: none;', id: 'new-message-submit' %>
  <% end %>
</div>

app/views/conversations/_conversation_status.erb
<% if conversation.status == 1 %>
  <div id="conversation_status" class="present">
    <div class="conversation-hourglass"></div>
    <div class="conversation-loading-label">
      <% if conversation.status_message.present? %>
        <%= conversation.status_message %>
      <% end %>
    </div>  
    <%= link_to('cancel request', cancel_processing_conversation_path(id: conversation.id)) %>
  </div>
<% else %>
  <div id='conversation_status'></div>
<% end %>

app/views/conversations/_currently_selected_document.html.erb
<tr id="document-<%= document.id %>-context-row">
  <td>
    <%= document.title %>
  </td>
    <td>
  <%= button_to toggle_context_conversation_path(id: conversation.id, document_id: document.id), method: :patch, form: { id: "current-document-#{document.id}" } do %>
      <i class="fa-solid fa-file-circle-minus fa-lg"></i>
  <% end %>
    </td>
</tr>

app/views/conversations/_gpt_cost_limit.html.erb
<%= turbo_stream_from user.id, "mana-bar" %>
<div id='gpt_cost_bar'>
  <div class='mana-header'><i class="fa-solid fa-fire fa-fw"></i>Mana</div>
  <div class='mana-limit-bar'>
    <% if user.gpt_budget_available > 0 %>
      <div class='mana-filled' style="width: <%= user.percentage_gpt_fees_available %>%;"></div>
    <% end %>
  </div>
  <div class='mana-details'><%= "#{"%.2f" % (user.gpt_budget_available * 100)} out of #{user.gpt_fees_limit.to_i * 100} MP available" %></div>
</div>

app/views/conversations/_message.html.erb
<% if message.role == 'user' %>
  <div class='message user' id='message-<%= message.id %>'>
    <div class='content'>
      <div tabindex="0" class='main-message'>
        <div class='message-controls' id="message-controls">
          <div class="button-wrapper">
            <i class="fa-regular fa-copy copy-icon fa-fw" onClick=<%= "copyContent('main-answer-#{message.id}');" %>></i>
          </div>
          <div class='button-wrapper'>
            <i class="fa-solid fa-trash fa-fw delete-icon delete-document-from-editor" onClick="document.getElementById('delete-message-button-<%= message.id %>').click();"></i>
          </div>
          <%= button_to "❌", delete_message_conversation_path(message.conversation, message_id: message.id), method: :delete, id: "delete-message-button-#{message.id}",
          form: { style: 'display:none;' } %>
        </div>
        <div class='main-message-content'>
          <div id=<%= "main-answer-#{message.id}" %>><%= simple_format message.content.gsub("\n", "<br>"), {}, {sanitize: false} %></div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class='message wroom' id='message-<%= message.id %>'>
    <div class='content'>
      <div tabindex="0" class='main-message'>
        <div class='main-message-content'>
          <div id=<%= "main-answer-#{message.id}" %>><%= simple_format message.content.gsub("\n", "<br>"), {}, {sanitize: false} %></div>
        </div>
        <div class='message-controls' id="message-controls">
          <div class="button-wrapper">
            <i class="fa-regular fa-copy copy-icon fa-fw" onClick=<%= "copyContent('main-answer-#{message.id}');" %>></i>
          </div>
          <div class='button-wrapper'>
            <i class="fa-solid fa-trash fa-fw delete-icon delete-document-from-editor" onClick="document.getElementById('delete-message-button-<%= message.id %>').click();"></i>
          </div>
        </div>
      <%= button_to "❌", delete_message_conversation_path(message.conversation, message_id: message.id), method: :delete, id: "delete-message-button-#{message.id}",
      form: { style: 'display:none;' } %>
    </div>
      <% if message.partial_answers.present? %>
        <details class='partial-answers'>
          <summary>Alternative answers:</summary>
          <% message.partial_answers.each_with_index do |answer, index| %>
            <div tabindex="0" class="message partial">
              <div class='message-controls' id="message-controls">
                <div class="button-wrapper">
                  <i class="fa-regular fa-copy copy-icon fa-fw" onClick=<%= "copyContent('partial-answer-#{message.id}-#{index}');" %>></i>
                </div>
              </div>
              <div id="<%= "partial-answer-#{message.id}-#{index}" %>">
                <%= simple_format answer %>
              </div>
            </div>
          <% end %>
        </details>
      <% end %>
    </div>
  </div>
<% end %>

app/views/conversations/_tree_document.html.erb
<% linked = conversation.documents.include?(document) %>
<%= button_to toggle_context_conversation_path(id: conversation.id, document_id: document.id), method: :patch, form: { class: 'document', id: "context-tree-document-#{document.id}" }, class: "document-button #{linked ? 'linked' : ''}" do %>
  <div class='document'>
    <% if document.source_based %>
      <i class="fa fa-book fa-fw" aria-hidden="true"></i>
    <% else %>
      <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
    <% end %>
    <%= document.title %>
  </div>
<% end %>

app/views/conversations/_tree_folder.html.erb
<script>
  function displayChildren(id) {
    const children = document.getElementById(id).children[1]
    if (children.style.display == 'flex')
      children.style.display = 'none';
    else
    children.style.display = 'flex';
  }
</script>
<div class='folder' id="<%= "context-tree-folder-#{folder.id}" %>">
  <div class="parent" onClick=<%= "displayChildren('context-tree-folder-#{folder.id}')" %>>
    <i class="fa-solid fa-caret-down fa-sm <%= folder.empty? ? 'invisible' : ''%>"></i>
    <i class="fa-regular fa-folder fa-fw"></i><%= folder.type == 'RootFolder' ? 'My Files' : folder.name %>
  </div>
  <div class="children" style="<%= folder.type == 'RootFolder' ? "" : "display: none;" %>">
    <% folder.children.kept.each do |folder| %>
      <%= render 'tree_folder', folder: folder %>
    <% end %>
    <% folder.documents.kept.each do |document| %>
      <%= render 'tree_document', document: document, conversation: @conversation %>
    <% end %>
  </div>
</div>

app/views/conversations/chat.html.erb
<%= turbo_frame_tag "conversation_frame" do %>
  <%= turbo_stream_from @conversation.id, 'conversation_status' %>
  <div id="chat">
    <%#= TODO:  Move 'settings' to a partial %>
    <div id='settings'>
      <%= link_to 'Context', context_conversation_path(@conversation) %>
      <%= form_with(
        model: @conversation,
        url: update_settings_conversation_url
      ) do |form| %>
        <% if @conversation.user.voices.kept.present? %>
          <div class='label-wrapper' onClick="openSelect();">
            <i class="fa-solid fa-robot fa-fw" style='margin-right: 0.3rem; margin-top: -0.1rem;'></i>
            <%= form.label 'Persona:', style: "display: block" %>
          </div>
          <%= form.collection_select :voice_id, @conversation.user.voices.kept.order(:name), :id, :name, { include_blank: "Default", selected: @conversation.voice.try(:id) }, onchange: "this.form.submit();" do |voice| %>
            <option value="<%= voice.id %>">
              <%= voice.name.length > 15 ? voice.name.slice(0, 15) + '...' : voice.name %>
            </option>
          <% end %>        
        <% end %>
        <%= form.submit style: 'display:none;' %>
      <% end %>
      <%= button_to('Clear chat', clear_chat_conversation_path(conversation_id: @conversation.id), method: :delete) %>
    </div>
    <%= render 'conversation', conversation: @conversation %>
  </div>
<% end %>

app/views/conversations/context.html.erb
<%= turbo_frame_tag "conversation_frame" do %>
  <%= turbo_stream_from @conversation.id, "conversation_context" %>
  <div class="context">
    <div class='header'>
      <%= link_to chat_conversation_path(@conversation) do %>
        <span>Back to chat</span><i class="fa-solid fa-rotate-left"></i>
      <% end %>
    </div>
    <div class='currently-selected'>
      <div class='current-context-header'>
        <h3>What this chat currently knows:</h3>
        <%= link_to 'Clear context', clear_context_conversation_path(@conversation), class: 'clear-context' %>
      </div>
      <div class='context-table-container'>
        <table id='currently-selected-context-table'>
          <tr>
            <th>
            </th>
            <th>
            </th>
          </tr>
          <% @conversation.documents.each do |document| %>
            <%= render 'conversations/currently_selected_document', document: document, conversation: @conversation %>
          <% end %>
        </table>
      </div>
    </div>
    <div class='folders'>
      <%= render 'tree_folder', folder: current_user.root_folder %>
    </div>
  </div>
<% end %>