config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :documents, except: %i[show index create] do
    member do
      patch 'autosave'
      get 'editor'
      get 'undiscard'
      get 'duplicate'
      get 'discard'
      post 'share'
    end
  end
  resources :folders do
    member do
      get 'explorer'
      get 'undiscard'
    end
    collection do
      get 'recycle_bin'
      delete 'empty_recycle_bin'
    end
  end
  resources :voices, except: :show do
    collection do
      get 'manager'
    end
    member do
      get 'undiscard'
    end
  end
  mount ActionCable.server => '/cable'
  mount DeviseMailerPreview, at: 'mail_view' if Rails.env.development?

  resources :conversations, only: [] do
    member do
      post 'new_message'
      get 'chat'
      get 'context'
      delete 'delete_message'
      get 'settings'
      patch 'update_settings'
      delete 'clear_chat'
      get 'cancel_processing'
      patch 'toggle_context'
      get 'clear_context'
    end
  end
  resources :sources, except: [:index]
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  resources :users, except: %i[new create index] do
    member do
      get 'toggle_gpt_4'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  ActiveAdmin.routes(self)

  patch '/drag/folder', to: 'drag#folder'
  patch '/drag/document', to: 'drag#document'
  get '/monitoring', to: 'monitoring#index'
  get '/wroom', to: 'wroom#app'
  get '/billing', to: 'subscriptions#subscriptions'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/redeem_referral_code', to: 'subscriptions#redeem_referral_code'
  get '/upgrade_subscription', to: 'subscriptions#upgrade_subscription'
  post '/stripe_webhook', to: 'subscriptions#stripe_webhook'
  get '/purchase_success', to: 'subscriptions#purchase_success'
  get '/dashboard', to: 'wroom#dashboard'
  get '/shared', to: 'wroom#shared'
  post '/ImportScreenplay', to: 'screenplayimporter#import_screenplay'
  get '/ImportScreenplayTest', to: 'screenplayimporter#test_form'
  root 'wroom#dashboard'
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord # rubocop:disable Metrics/ClassLength
  include Discard::Model
  belongs_to :user
  belongs_to :folder
  has_one :source, dependent: :destroy
  has_one :conversation, dependent: :destroy
  has_many :context_references, dependent: :destroy
  has_many :documents, through: :context_references
  has_one :etherpad_group, dependent: :destroy
  has_many :document_collaborations, dependent: :destroy
  has_many :collaborators, through: :document_collaborations, source: :user
  has_rich_text :content

  validates :title, presence: true
  has_many :monitoring_events, as: :trackable, dependent: :nullify

  after_create_commit :log_event
  after_create_commit :create_conversation
  after_create_commit :broadcast_create
  after_create_commit :update_storage_bar
  after_discard :remove_document_row
  before_destroy :remove_document_row
  before_destroy :update_storage_bar
  after_discard :remove_from_sidebar
  after_save :remove_document_row, if: :saved_change_to_folder_id?

  def share_with(user)
    document_collaborations.create!(user_id: user.id)
  end

  # TODO: Handle Etherpad errors
  def initialize_etherpad
    initialize_etherpad_group
    initialize_etherpad_pad
  end

  def initialize_etherpad_group
    return unless etherpad_group.nil?

    ether = EtherpadService.new.ether
    group = ether.create_group
    create_etherpad_group(group_id: group.id)
  end

  def initialize_etherpad_pad # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    return unless etherpad_pad_id.nil?

    srv = EtherpadService.new
    pad_id = "#{etherpad_group.group_id}$wroom_document_#{id}"
    text = content.present? ? [content.body.to_plain_text] : ['']
    if srv.pad_ids.include? pad_id
      srv.ether.client.setText(
        padID: pad_id,
        text: text[0]
      )
    else
      pad = srv.ether.client.createGroupPad(
        groupID: etherpad_group.group_id,
        # TODO: Obscure document id in pad name
        padName: "wroom_document_#{id}",
        text:,
        authorId: [user.etherpad_author_id]
      )
      pad_id = pad[:padId]
    end

    update!(etherpad_pad_id: pad_id)
  end

  def clone_pad(document)
    return if document.etherpad_pad_id.nil?

    initialize_etherpad_group

    srv = EtherpadService.new
    pad_id = "#{etherpad_group.group_id}$wroom_document_#{id}"

    srv.ether.client.copyPad(
      sourceID: document.etherpad_pad_id,
      destinationID: pad_id
    )
    update!(etherpad_pad_id: pad_id)
  end

  def etherpad_pad_text_content
    return nil if etherpad_pad_id.nil?

    ether = EtherpadService.new.ether
    ether.get_pad(etherpad_pad_id).text.gsub(/[\t\n]+/, ' ')
  end

  def remove_from_sidebar
    broadcast_remove_to(
      user.id,
      'sidebar_explorer',
      target: "tree-document-#{id}"
    )
  end

  def truncated_title(length)
    if title.length <= length
      title
    else
      title.truncate(length, separator: ' ')
    end
  end

  def refresh_source
    Source.where(document_id: id).destroy_all
    source = Source.create!(name: title, user_id:, document_id: id, fileless: true)
    source.parse_source_chunks_from_text(etherpad_pad_text_content)
  end

  def broadcast_create # rubocop:disable Metrics/MethodLength
    broadcast_after_to(
      user.id,
      'folder_documents',
      partial: 'folders/document_row',
      locals: { document: self, in_query: false },
      target: "document-row-#{cloned_from}"
    )
    broadcast_after_to(
      user.id,
      'sidebar_explorer',
      partial: 'folders/tree_document',
      locals: { document: self },
      target: "tree-document-#{cloned_from}"
    )
  end

  def update_storage_bar
    broadcast_replace_to(
      user.id,
      'storage-bar',
      partial: 'documents/storage_limit',
      locals: { user: },
      target: 'storage_bar'
    )
  end

  def remove_document_row
    broadcast_remove_to(
      user.id,
      'folder_documents',
      target: "document-row-#{id}"
    )
  end

  def path
    build_path(self)
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[cloned_from created_at discarded_at folder_id id source_based title updated_at user_id]
  end

  private

  def build_path(document)
    if document.folder.parent && !document.folder.type == 'RootFolder'
      File.join(build_path(document.folder.parent), document.folder.name, document.title)
    else
      File.join('/', document.folder.name, document.title)
    end
  end

  def log_event
    monitoring_events.create!(user_id: user&.id, note: "#{user&.email} created document #{title}",
                              event_type: 'create_record')
  end

  def create_conversation
    Conversation.create!(title:, document_id: id)
    ContextReference.create!(document_id: id, conversation_id: conversation.id)
  end
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

class DocumentsController < ApplicationController # rubocop:disable Metrics/ClassLength
  before_action :set_document,
                only: %i[editor destroy autosave undiscard discard share]
  load_and_authorize_resource

  def share # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    email = params[:email]
    user = User.find_by(email:)
    # TODO: Refactor this logic into a service object, e.g. CollaborationService
    if user.nil?
      PendingCollaboration.create!(document_id: @document.id, invited_by: current_user.email, email:)
      redirect_to editor_document_path(@document),
                  notice: 'This user does not have an account yet. We have sent them an invitation to join Wroom.'
    elsif user == current_user
      redirect_to editor_document_path(@document), alert: 'You cannot share a document with yourself'
    elsif @document.collaborators.include?(user)
      redirect_to editor_document_path(@document), notice: 'This user already has access to this document'
    else
      @document.share_with(user)
      redirect_to editor_document_path(@document), notice: 'Document shared successfully'
    end
  end

  def editor # rubocop:disable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
    # TODO: Refactor this method
    @document = if params[:id].present?
                  Document.find(params[:id])
                else
                  current_user.documents.first
                end
    # Initializes etherpad if not already done
    # TODO: Move this into a Document model callback
    if !@document.source_based && (@document.etherpad_group.nil? || @document.etherpad_pad_id.nil?)
      @document.initialize_etherpad
    end
    @conversation = @document.conversation
    # TODO: Move breadcrumb logic out of this method
    @document.folder.parents.reverse.each do |parent|
      breadcrumbs << Breadcrumb.new(parent.name, folder_path(parent))
    end
    breadcrumbs << Breadcrumb.new(@document.folder.name, folder_path(@document.folder))
    breadcrumbs << Breadcrumb.new(@document.truncated_title(40), editor_document_path(@document))

    return if @document.source_based

    # TODO: Move the logic below into EtherpadService for better separation of concerns
    ether = EtherpadService.new.ether
    author = ether.get_author(current_user.etherpad_author_id)
    group = ether.get_group(@document.etherpad_group.group_id)

    # TODO: Handle session logic in a separate method in this controller
    session[:ep_sessions] = {} if session[:ep_sessions].nil?
    sess = if session[:ep_sessions][group.id]
             ether.get_session(session[:ep_sessions][group.id])
           else
             group.create_session(
               author, 60 * 24
             )
           end
    if sess.expired?
      sess.delete
      sess = group.create_session(author, 60)
    end
    session[:ep_sessions][group.id] = sess.id
    cookies['sessionID'] = {
      value: sess.id,
      domain: ENV['COOKIES_DOMAIN']
    }
    cookies['prefsHttp'] = {
      value: {},
      domain: ENV['COOKIES_DOMAIN']
    }

    @etherpad_url = ENV['ETHERPAD_URL']
    @etherpad_url += '/p/'
    @etherpad_url += @document.etherpad_pad_id
  end

  def index
    @documents = Document.kept
    @users = User.where.not(id: current_user.id) if current_user.admin?
  end

  def undiscard
    @document.undiscard
    redirect_to wroom_path(document_id: @document.id)
  end

  def new
    @document = Document.create!(
      title: 'Untitled',
      user_id: current_user.id,
      folder_id: current_user.current_folder_id || current_user.root_folder.id
    )
    @document.initialize_etherpad
    redirect_to wroom_path(document_id: @document.id)
  end

  def autosave
    @document.assign_attributes(document_params)
    @document.save!
    head :ok
  end

  def duplicate # rubocop:disable Metrics/AbcSize, Metrics/MethodLength, Metrics/CyclomaticComplexity, Metrics/PerceivedComplexity
    # TODO: Move this into Document model
    @document = Document.find(params[:id])
    duplicate = @document.dup
    duplicate.cloned_from = @document.id
    duplicate.title = "#{@document.title} Copy"
    duplicate.content = @document.content
    duplicate.etherpad_pad_id = nil
    duplicate.save!

    # Initializes etherpad for cloned document if for some reason the original is missing its etherpad_pad_id
    # Otherwise clones the original's pad
    if @document.etherpad_pad_id.nil?
      duplicate.initialize_etherpad
    else
      duplicate.clone_pad(@document)
    end
    # Copies the chat to the new document
    conversation = @document.conversation.dup
    if @document.conversation.messages.present?
      @document.conversation.messages.each do |message|
        conversation.messages << message.dup
      end
    end
    # Copies the voice to the new document
    conversation.voice = @document.conversation.voice if @document.conversation.voice.present?
    conversation.save!
    # Copies over context references
    if @document.conversation.context_references.present?
      @document.conversation.context_references.each do |reference|
        ContextReference.create!(document_id: reference.document_id, conversation_id: conversation.id)
      end
    end
    duplicate.conversation = conversation
    duplicate.save!
    # Copies over the source if the original document has one
    if @document.source.present?
      source = @document.source.dup
      @document.source.source_chunks.each do |chunk|
        source.source_chunks << chunk.dup
      end
      source.file.attach @document.source.file.blob
      source.save!
      duplicate.source = source
      duplicate.save!
    end
    @document.update_storage_bar
    head :no_content
  end

  def discard
    @document.discard
    current_user.update!(current_document_id: nil) if current_user.current_document_id == @document.id
    head :no_content
  end

  def destroy
    @document.destroy
    head :no_content
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :content, :user_id, :folder_id)
  end
end

app/views/documents/_chunking_status.html.erb
<%= turbo_frame_tag "chunking_status" do %>
  <div class='chunking-status-notice'>
    <% if chunk.ordinal_number >= chunk.document.document_chunks.pluck(:ordinal_number).max %>
      <p>Done!</p>
      <script>
        setTimeout(() => { location.reload() }, 1000)
      </script>
    <% else %>
      <div class="lds-hourglass"></div>
      <p>Creating chunk <%= "#{chunk.ordinal_number + 2}..." %></p>
    <% end %>
  </div>

<% end %>

app/views/documents/_document.html.erb
<div class='record-info'>
  <div class='field'>
    <label>Name:</label>
    <%= document.name %>
  </div>
  <div class='field'>
    <label>Title:</label>
    <%= document.title %>
  </div>
  <div class='field'>
    <label>Author:</label>
    <%= document.author %>
  </div>
  <div class='field'>
    <label>Year published:</label>
    <%= document.year_published %>
  </div>
  <div class='field'>
    <label>Section headers:</label>
    <%= document.section_headers.join(', ') %>
  </div>
  <div class='field'>
    <label>File:</label>
    <% if document.file.attached? %>
      <%= link_to document.file.filename, rails_blob_path(document.file, disposition: 'attachment') %>
    <% else %>
      None attached
    <% end %>
  </div>
  <div class='field'>
    <label>User:</label>
    <%= document.user_id %>
  </div>
</div>

app/views/documents/_document_share_modal.html.erb
<script>
  if (document.getElementById('share-modal-button')) {
    let modalButton = document.getElementById('share-modal-button');
    let modalOverlay = document.getElementById('modal-overlay');

    modalButton.addEventListener('click', function() {
      modalOverlay.style.display = 'block';
    });

    let closeModal = document.getElementById('close-modal');
    closeModal.addEventListener('click', function() {
      modalOverlay.style.display = 'none';
    });

    modalOverlay.addEventListener('click', function(event) {
      if (event.target === modalOverlay) {
        modalOverlay.style.display = 'none';
      }
    });
  }

</script>
<div id="modal-overlay">
  <div id="modal">
    <span id="close-modal"><i class="fa-solid fa-circle-xmark"></i></span>
    <h2><i class="fa-solid fa-share-nodes fa-fw"></i><%= document.title %></h2>
    <p>
      <% if document.collaborators.empty? %>
        This document is not yet shared with anyone.
      <% else %>
        This document is currently shared with:
        <ul>
          <% document.collaborators.each do |collaborator| %>
            <li><%= collaborator.email %></li>
          <% end %>
        </ul>
      <% end %>
    </p>
    <h2>Share this document</h2>
    <p>
      You will be able to see each other's changes in real-time, and
      chat with each other using the chat feature.
    </p>
    <p>
      If the user does not have a Wroom account, they will be sent an
      email inviting them to create one.
    </p>
    <form action="/documents/<%= document.id %>/share" method="post" id='document-share-form'>
      <input type="email" name="email" placeholder="Email address" required>
      <input type="hidden" name="id" value="<%= document.id %>">
      <button type="submit">Share</button>
    </form>
  </div>
</div>

app/views/documents/_form.html.erb
<div class="record-form">
  <%= form_with(
    model: document
  ) do |form| %>
    <% if document.errors.any? %>
      <div class='validation'>
        <div class='message'>
          <%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:
        </div>
        <div class='errors'>
          <% document.errors.each do |error| %>
            <div class='error'><span class='bullet'>• </span><%= error.full_message %></div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class='field'>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title, { onchange: action_name == 'new' ? '' : 'this.form.submit()' } %>
    </div>

    <% if current_user.admin? %>
      <div class='field'>
        <%= form.label :user_id, style: "display: block" %>
        <%= form.collection_select :user_id, User.all, :id, :email, { selected: action_name == 'new' ? current_user.id : document.user_id , readonly: true } %>
      </div>
    <% else %>
      <div class='field' style='display: none;'>
        <%= form.label :user_id, style: "display: block" %>
        <%= form.text_field :user_id, value: current_user.id, readonly: cannot?(:manage, User) %>
      </div>
    <% end %>
    <div class='field'>
      <%= form.submit %>
    </div>

  <% end %>
</div>

app/views/documents/_storage_limit.html.erb
<%#= TODO: Move this partial to app/views/storage/storage_limit %>
<%#= TODO: Remember to adjust app/models/document.rb to match%>
<%= turbo_stream_from user.id, "storage-bar" %>
<div id='storage_bar'>
  <div class='storage-header'><i class="fa-solid fa-cloud fa-fw"></i>Storage</div>
  <div class='storage-limit-bar'>
    <% if user.storage_used > 0 %>
      <div class='storage-filled' style="width: <%= user.percent_storage_used %>%;"></div>
    <% end %>
  </div>
  <div class='storage-details'><%= "#{number_to_human_size(user.storage_used)} out of #{number_to_human_size(user.total_storage)} used" %></div>
</div>

app/views/documents/editor.html.erb
<%= turbo_frame_tag "document_editor" do %>
  <div id='document-editor-background'>
    <%= render partial: 'layouts/breadcrumbs' %>
    <div id='document-editor'>
      <div id="document-panel" class="panel">
        <div id='edit-document'>
          <% if @document.source_based %>
            <%= render 'sources/show', source: @document.source %>
          <% else %>
            <%= form_with(
                model: @document,
                data: {controller: 'document', autosave_delay: '250'},
                id: 'edit-document'
            ) do |form| %>
                <div class='top-pane'>
                  <%= form.text_field :title, data: { action: "keyup->document#save blur->document#save" } %>
                  <% if @document.user == current_user %>
                    <div class='right-buttons'>
                      <a id='share-modal-button' <%= @document.collaborators.any? ? "class=has-collaborators" : ""  %>>
                        <i class="fa-solid fa-share-nodes fa-fw"></i>Share
                      </a>
                    </div>
                  <% else %>
                    <div class='right-buttons'>
                      <a class='has-collaborators unclickable'>
                        <i class="fa-solid fa-share-nodes fa-fw"></i>Collaborating
                      </a>
                    </div>
                  <% end %>
                </div>
            <% end %>
            <%= render partial: 'layouts/flash_messages' %>
            <%= render partial: 'document_share_modal', locals: { document: @document } if @document.user == current_user %>
            <iframe src="<%= @etherpad_url %>" id="etherpad-frame"></iframe>
          <% end %>
        </div>
      </div>
      <div id="conversation-panel" class="panel">
        <% if @document.conversation %>
          <%= turbo_frame_tag "conversation_frame", src: chat_conversation_path(@document.conversation) %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/documents/new.html.erb
<%= turbo_frame_tag 'view_content' do %>
  <div id="record-form-view">
    <div id="record-form-box">
      <div id="header">
        <h3>New document</h3>
        <%= link_to "❌", root_path %>
      </div>

      <%= form_with(
        model: @document
      ) do |form| %>
        <% if @document.errors.any? %>
          <div class='validation'>
            <div class='message'>
              <%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:
            </div>
            <div class='errors'>
              <% @document.errors.each do |error| %>
                <div class='error'><span class='bullet'>• </span><%= error.full_message %></div>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class='field' style='display: none;'>
          <%= form.text_field :folder_id, value: @folder_id, readonly: cannot?(:manage, User) %>
        </div>
        <div class='field-with-submit'>
          <%= form.text_field :title %>
          <%= form.submit 'Confirm' %>
        </div>
        <div class='field' style='display: none;'>
          <%= form.text_field :user_id, value: current_user.id, readonly: cannot?(:manage, User) %>
        </div>

      <% end %>

    </div>
  </div>
<% end %>

app/views/documents/new_frame.html.erb
  <%= turbo_frame_tag "new_document_frame" do %>
    <%= form_with(
      model: @document,
      url: create_from_frame_documents_url,
      id: 'new-document'
    ) do |form| %>

      <%= form.text_field :title, { placeholder: 'New project name' } %>
      <%= form.text_field :user_id, value: current_user.id, style: 'display: none;', readonly: cannot?(:manage, User) %>
      <%= form.submit '✙', style: 'font-style: normal;' %>

    <% end %>
  <% end %>

app/views/documents/show.html.erb
<%= turbo_stream_from @document.id, 'chunking_status' %>
<div id='view-header'>
  <h1><%= @document.name || @document.title || "Untitled" %></h1>
  <%= link_to "✍︎", edit_document_path(@document) %>
</div>
<div id='view-content'>
  <div class='show-record'>
    <%= render @document %>
    <% if @document.document_chunks.count > 1 %>
      <h3>Chunks</h3>
      <% @document.document_chunks.each do |chunk| %>
        <div class='chunk'>
          <details>
            <summary>
              <%= "Chunk #{chunk.ordinal_number + 1}: #{chunk.section_header.strip}" %>
            </summary>
            <p>
              <%= chunk.content %>
            </p>
          </details>
        </div>
      <% end %>
    <% elsif @document.document_chunks.count == 1 %>
    <div class='chunk'>
      <p>
        <%= @document.document_chunks.first.content %>
      </p>
    </div>
    <% elsif @document.document_chunks.count == 0 %>
      <%= turbo_frame_tag 'chunking_status' do %>
        <div class='chunking-status-notice'>
          <div class="lds-hourglass"></div>
          <p><i>processing your document...</i></p>
          <p><i>if you experience a delay of more than a few seconds, </i></p>
          <p><i>try reloading the page<i></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>