config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resources :documents, except: %i[show index create] do
    member do
      patch 'autosave'
      get 'editor'
      get 'undiscard'
      get 'duplicate'
      get 'discard'
      post 'share'
    end
  end
  resources :folders do
    member do
      get 'explorer'
      get 'undiscard'
    end
    collection do
      get 'recycle_bin'
      delete 'empty_recycle_bin'
    end
  end
  resources :voices, except: :show do
    collection do
      get 'manager'
    end
    member do
      get 'undiscard'
    end
  end
  mount ActionCable.server => '/cable'
  mount DeviseMailerPreview, at: 'mail_view' if Rails.env.development?

  resources :conversations, only: [] do
    member do
      post 'new_message'
      get 'chat'
      get 'context'
      delete 'delete_message'
      get 'settings'
      patch 'update_settings'
      delete 'clear_chat'
      get 'cancel_processing'
      patch 'toggle_context'
      get 'clear_context'
    end
  end
  resources :sources, except: [:index]
  devise_for :users, controllers: {
    confirmations: 'confirmations',
    registrations: 'registrations',
    sessions: 'sessions'
  }
  resources :users, except: %i[new create index] do
    member do
      get 'toggle_gpt_4'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  ActiveAdmin.routes(self)

  patch '/drag/folder', to: 'drag#folder'
  patch '/drag/document', to: 'drag#document'
  get '/monitoring', to: 'monitoring#index'
  get '/wroom', to: 'wroom#app'
  get '/billing', to: 'subscriptions#subscriptions'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/redeem_referral_code', to: 'subscriptions#redeem_referral_code'
  get '/upgrade_subscription', to: 'subscriptions#upgrade_subscription'
  post '/stripe_webhook', to: 'subscriptions#stripe_webhook'
  get '/purchase_success', to: 'subscriptions#purchase_success'
  get '/dashboard', to: 'wroom#dashboard'
  get '/shared', to: 'wroom#shared'
  post '/ImportScreenplay', to: 'screenplayimporter#import_screenplay'
  get '/ImportScreenplayTest', to: 'screenplayimporter#test_form'
  root 'wroom#dashboard'
end

app/controllers/wroom_controller.rb
# frozen_string_literal: true

class WroomController < ApplicationController
  # TODO: Create a separate DashboardController and move this logic there
  def dashboard
    @current_folder = params[:current_folder_id].present? ? Folder.find(params[:current_folder_id]) : @root_folder
    render layout: 'dashboard'
  end

  # TODO: Create a separate DashboardController and move this logic there
  def shared
    @shared_folder = current_user.shared_folder
    @documents = current_user.collaborated_documents.kept
    render layout: 'dashboard'
  end

  def app # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
    @document = if params[:document_id].present?
                  Document.find(params[:document_id])
                elsif current_user.current_document_id.present?
                  Document.find(current_user.current_document_id)
                elsif current_user.documents.kept.any?
                  current_user.documents.kept.first
                end
    if @document
      current_user.update!(current_document_id: @document.id)
    else
      redirect_to explorer_folder_path(current_user.root_folder)
    end
    render layout: 'wroom'
  end
end

app/views/wroom/_new_button.html.erb
<script>
  function showNewOptions() {
    const options = document.getElementsByClassName('options')[0];
    const button = document.getElementById('new-button');
    options.style.display = 'flex';
    button.addEventListener('click', hideOptions)
    document.body.addEventListener('click', function(e) {
      if (options.contains(e.target) || button.contains(e.target)) {
        // hideOptions();
      } else {
        hideOptions();
      }
    })
  }
  function hideOptions() {
    const options = document.getElementsByClassName('options')[0];
    const button = document.getElementById('new-button');
    button.removeEventListener('click', hideOptions)
    button.addEventListener('click', showNewOptions)
    options.style.display = 'none';
  }
</script>
<div class="new">
  <div class="button" onClick="showNewOptions();" id="new-button">
    <i class="fa-solid fa-wand-magic-sparkles fa-xs" style="color: #ffffff;"></i><span>Create</span>
  </div>
  <div class="options" style="display: none;">
    <%= link_to new_folder_path, data: { turbo_action: 'replace', turbo_frame: 'view_content' } do %>
      <i class="fa fa-folder-plus fa-fw"></i><span>New folder</span>
    <% end %>
    <%= link_to new_document_path, data: { turbo_action: 'replace', turbo_frame: '_top' } do %>
      <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i><span>New Wroom Doc</span>
    <% end %>
    <a href="#" onclick="document.getElementById('source-file-field').click(); return false;">
      <i class="fa fa-book fa-fw" aria-hidden="true"></i><span>Upload file</span>
    </a>
    <%= link_to manager_voices_path do %>
      <i class="fa-solid fa-robot fa-fw"></i><span>Create Persona</span>
    <% end %>
  </div>
</div>
<div style='display: none;'>
  <%= form_with(
    model: @new_source,
    data: {
      controller: 'form-redirect',
      action: 'turbo:submit-end->form-redirect#next'
    },
    html: { 
      id: 'source-form',
      onchange: 'document.getElementById("bean-eater").style.display = "flex"; document.getElementById("source-form").submit();'
    }
  ) do |form| %>
    <%= form.label :file %>
    <%= form.file_field :file, id: 'source-file-field', multiple: true %>
    <%= form.text_field :user_id, value: current_user.id, readonly: cannot?(:manage, User) %>
  <% end %>
</div>

app/views/wroom/_tree_document.html.erb
<%= link_to editor_document_path(document), data: { turbo_frame: 'document_editor' } do %>
  <div class='tree-document' id="tree-document-<%= document.id %>">
    <% if document.source_based %>
      <i class="fa fa-book fa-fw" aria-hidden="true"></i>
    <% else %>
      <i class="fa fa-file-text-o fa-fw" aria-hidden="true"></i>
    <% end %>
    <%= document.title %>
  </div>
<% end %>

app/views/wroom/_tree_folder.html.erb
<script>
  function displayChildren(id) {
    const children = document.getElementById(id).children[1]
    if (children.style.display == 'flex')
      children.style.display = 'none';
    else
    children.style.display = 'flex';
  }
</script>
<div class='tree-folder' id="<%= "tree-folder-#{folder.id}" %>">
  <div class="parent" onClick=<%= "displayChildren('tree-folder-#{folder.id}')" %>>
    <i class="fa-regular fa-folder fa-fw"></i>
    <%= folder.type == 'RootFolder' ? 'My Files' : folder.name %>
    <% if !folder.empty? %>
      <i class="fa-solid fa-caret-down fa-sm"></i>
    <% else %>
      <span class='spacer'></span>
    <% end %>
  </div>
  <div class="children" style="<%= folder.type == 'RootFolder' ? "" : "display: none;" %>">
    <% folder.children.kept.each do |folder| %>
      <%= render 'tree_folder', folder: folder %>
    <% end %>
    <% folder.documents.kept.each do |document| %>
      <%= render 'tree_document', document: document %>
    <% end %>
  </div>
</div>

app/views/wroom/app.html.erb
<%= turbo_frame_tag "document_editor", src: editor_document_path(@document) %>

app/views/wroom/dashboard.html.erb
<%= turbo_frame_tag "view_content", src: folder_path(@current_folder) %>

app/views/wroom/shared.html.erb
<%= turbo_frame_tag "view_content" do %>
  <div class='header'>
    <span>Shared with me</span>
  </div>
  <% if @documents.empty? %>
    <div class='empty'>
      <span>No documents have been shared with you.</span>
    </div>
  <% else %>
    <%= render "folders/records_table", folder: @shared_folder, documents: @documents, folders: nil %>
  <% end %>
<% end %>